---
collections:
  - name: community.aws.aws_ssm
  - name: community.mysql
  - name: amazon.aws
  - name: community.aws
    version: ">=5.0.0"
  - name: ansible.posix
    version: ">=1.5.0"
  - name: community.general
    version: ">=7.0.0"
  - name: kubernetes.core
    version: ">=3.0.0"
