# inventory/aws_ec2.yaml

plugin: amazon.aws.aws_ec2

regions:
  - us-east-1

filters:
  instance-state-name: running

hostnames:
  - ip-address
  - private-ip-address

compose:
  ansible_host: public_ip_address | default(private_ip_address)

keyed_groups:
  - key: ec2_tags.Name
    prefix: tag_Name
    separator: "_"
