---
- name: Deploy sysctl security hardening configuration
  ansible.builtin.template:
    src: sysctl_hardening.conf.j2
    dest: /etc/sysctl.d/99-os-hardening.conf
    owner: root
    group: root
    mode: '0644'
  register: sysctl_deploy

- name: Reload sysctl kernel settings if modified
  ansible.builtin.command:
    cmd: "sysctl --system"
  when: sysctl_deploy.changed
  changed_when: true
