---
- name: Configure MariaDB server
  hosts: db_servers
  become: true
  gather_facts: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_files:
    - /home/GSK/ansible-lab/inventory/group_vars/vault.yml

  roles:
    - role: "../../roles/mariadb"
