---
- name: Configure MariaDB server
  hosts: db_servers
  become: true
  gather_facts: true
  vars_files:
    - "../../inventory/group_vars/vault.yml"   # Relative path from playbooks/ directory
  vars:
    ansible_python_interpreter: /usr/bin/python3

  roles:
    - role: "../../roles/mariadb"
