- name: Test ansible mysql module
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Create test database
      ansible.mysql.mysql_db:
        name: awx_test
        state: present
