---
- name: Test Semaphore connectivity
  hosts: all
  gather_facts: false

  tasks:
    - name: Test connectivity
      ansible.builtin.ping:

    - name: Show connected user
      ansible.builtin.command: whoami
      register: result
      changed_when: false

    - name: Display user
      ansible.builtin.debug:
        var: result.stdout

    - name: Display host IP
      ansible.builtin.debug:
        msg: "Target host IP is {{ ansible_host | default(inventory_hostname) }}"
