---
- name: Test Vault variable
  hosts: db_servers
  gather_facts: false
  vars_files:
    - /home/GSK/ansible-lab/inventory/group_vars/vault.yml

  tasks:
    - name: Check db password variable
      ansible.builtin.debug:
        msg: "db_password is loaded"
      when: db_password is defined
