---
- name: Standalone User & Group Provisioning Playbook
  hosts: db_servers
  become: true
  gather_facts: true
  roles:
    - role: common
      tags: [common, Always]
    - role: users
      tags: [users]
