---
# SPDX-License-Identifier: MIT-0

k8s_pod_network_cidr: "192.168.0.0/16"
k8s_service_cidr: "10.96.0.0/12"
k8s_cri_socket: "unix:///run/containerd/containerd.sock"

k8s_cni_manifest_url: "https://raw.githubusercontent.com/projectcalico/calico/v3.28.2/manifests/calico.yaml"
k8s_cni_manifest_path: /tmp/calico.yaml

k8s_admin_kubeconfig: /etc/kubernetes/admin.conf
k8s_kubeconfig_user: "{{ ansible_user | default(ansible_user_id) }}"
k8s_fetch_kubeconfig: true
k8s_fetch_kubeconfig_dest: "{{ playbook_dir }}/../kubeconfig"

k8s_join_token_ttl: "2h"
k8s_allow_control_plane_workloads: false

k8s_api_wait_retries: 36
k8s_api_wait_delay: 5
k8s_cni_wait_retries: 36
k8s_cni_wait_delay: 10
